/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc -c /home/madvib/dev/bene/apps/services/ai/wrangler.jsonc -c /home/madvib/dev/bene/apps/services/event-bus/wrangler.jsonc --env-file /home/madvib/dev/bene/.dev.vars` (hash: 58aad9e18127b584bfbe8141a0660f36)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UserHub";
	}
	interface Env {
		NODE_ENV: string;
		USER_HUB: DurableObjectNamespace<import("./src/index").UserHub>;
		PLAN_TEMPLATE_DB: D1Database;
		AI_SERVICE: Service<typeof import("../../services/ai/src/index").default>;
		EVENT_BUS: Service<typeof import("../../services/event-bus/src/index").default>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}