/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-file /home/madvib/dev/bene/.dev.vars` (hash: a32587e9fad046c30dcbface697a011a)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UserHub";
	}
	interface Env {
		NEXTJS_ENV: string;
		USER_AGENT: DurableObjectNamespace /* UserAgent */;
		AI_SERVICE: Fetcher /* ai-service */;
		EVENT_BUS: Fetcher /* event-bus */;
		PLAN_TEMPLATE_DB: D1Database;
	}
}
interface Env extends Cloudflare.Env { }
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV">> { }
}
declare module "*.sql" {
	const value: string;
	export default value;
}