/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-file /home/madvib/dev/bene/.dev.vars` (hash: 434ed0b57399317d2c89d46a4c98fad3)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		NEXTJS_ENV: string;
		DB_USER_AUTH: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV">> {}
}
