

/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc --env-file /home/madvib/dev/bene/.env.local --env-file .dev.vars` (hash: 23c2af1a94b168927ac7c009c166e653)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env {
		VITE_API_BASE_URL: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_USER_AUTH_DATABASE_ID: string;
		CLOUDFLARE_D1_TOKEN: string;
		NEXTJS_ENV: string;
		NEXT_PUBLIC_GATEWAY_URL: string;
		DB_USER_AUTH: D1Database;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env { }
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_API_BASE_URL" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_USER_AUTH_DATABASE_ID" | "CLOUDFLARE_D1_TOKEN" | "NEXTJS_ENV" | "NEXT_PUBLIC_GATEWAY_URL">> { }
}
