packages:
  - 'apps/**'
  - 'packages/**'
  - 'tools/*'
catalog:
  '@tanstack/react-query': '5.90.12'
  'better-auth': '1.4.7'
  agents: '0.2.32'
  drizzle-orm: '0.45.1'
  react: '^19.2.3'
  react-dom: '^19.2.3'
  zod: '4.2.1'
