export const APP_ERROR_CODES = {
  // General
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PARSE_ERROR: 'PARSE_ERROR',

  // Auth / Access
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Domain / Logic
  DOMAIN_ERROR: 'DOMAIN_ERROR',
  CONFLICT: 'CONFLICT',

  // Persistence
  REPOSITORY_ERROR: 'REPOSITORY_ERROR',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  QUERY_ERROR: 'QUERY_ERROR',
  SAVE_ERROR: 'SAVE_ERROR',
  DELETE_ERROR: 'DELETE_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',

  // AI
  AI_ERROR: 'AI_ERROR',

  // Specific Business Logic (Legacy/Specific)
  NO_ACTIVE_PLAN: 'NO_ACTIVE_PLAN',
} as const;

export type AppErrorCode = keyof typeof APP_ERROR_CODES;
