/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc --env-file /home/madvib/dev/bene/.env.local --env-file .dev.vars` (hash: 4be9ec3f979192ca2e8c015b44b41e07)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		VITE_API_BASE_URL: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_USER_AUTH_DATABASE_ID: string;
		CLOUDFLARE_D1_TOKEN: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_API_KEY: string;
		DEFAULT_PROVIDER: string;
		DEFAULT_MODEL: string;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
