/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc --env-file /home/madvib/dev/bene/.dev.vars --env-file .dev.vars` (hash: dadcfc65e30f8dab450893254477f338)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		NODE_ENV: string;
		ANTHROPIC_API_KEY: string;
		OPENAI_API_KEY: string;
		DEFAULT_PROVIDER: string;
		DEFAULT_MODEL: string;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
