/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-file /home/madvib/dev/bene/.dev.vars` (hash: e87ef52dfc76b5c2ac8ca45ce318e6a7)
export {};
declare global {
	const NEXTJS_ENV: string;
}
