/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as UserRouteRouteImport } from './routes/$user/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as marketingFeaturesRouteImport } from './routes/(marketing)/features'
import { Route as marketingAboutRouteImport } from './routes/(marketing)/about'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authCallbackRouteImport } from './routes/(auth)/callback'
import { Route as UserDashboardRouteRouteImport } from './routes/$user/_dashboard/route'
import { Route as UserChatRouteRouteImport } from './routes/$user/_chat/route'
import { Route as UserAccountRouteRouteImport } from './routes/$user/_account/route'
import { Route as UserDashboardTodayRouteImport } from './routes/$user/_dashboard/today'
import { Route as UserDashboardPlanRouteImport } from './routes/$user/_dashboard/plan'
import { Route as UserDashboardActivitiesRouteImport } from './routes/$user/_dashboard/activities'
import { Route as UserChatCoachRouteImport } from './routes/$user/_chat/coach'
import { Route as UserAccountSettingsRouteImport } from './routes/$user/_account/settings'
import { Route as UserAccountProfileRouteImport } from './routes/$user/_account/profile'
import { Route as UserAccountNotificationsRouteImport } from './routes/$user/_account/notifications'
import { Route as UserAccountConnectionsRouteImport } from './routes/$user/_account/connections'
import { Route as UserAccountBillingRouteImport } from './routes/$user/_account/billing'
import { Route as UserAccountAccountRouteImport } from './routes/$user/_account/account'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRouteRoute = UserRouteRouteImport.update({
  id: '/$user',
  path: '/$user',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingFeaturesRoute = marketingFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingAboutRoute = marketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => marketingRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authCallbackRoute = authCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => authRouteRoute,
} as any)
const UserDashboardRouteRoute = UserDashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserChatRouteRoute = UserChatRouteRouteImport.update({
  id: '/_chat',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserAccountRouteRoute = UserAccountRouteRouteImport.update({
  id: '/_account',
  getParentRoute: () => UserRouteRoute,
} as any)
const UserDashboardTodayRoute = UserDashboardTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => UserDashboardRouteRoute,
} as any)
const UserDashboardPlanRoute = UserDashboardPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => UserDashboardRouteRoute,
} as any)
const UserDashboardActivitiesRoute = UserDashboardActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => UserDashboardRouteRoute,
} as any)
const UserChatCoachRoute = UserChatCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => UserChatRouteRoute,
} as any)
const UserAccountSettingsRoute = UserAccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserAccountRouteRoute,
} as any)
const UserAccountProfileRoute = UserAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserAccountRouteRoute,
} as any)
const UserAccountNotificationsRoute =
  UserAccountNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => UserAccountRouteRoute,
  } as any)
const UserAccountConnectionsRoute = UserAccountConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => UserAccountRouteRoute,
} as any)
const UserAccountBillingRoute = UserAccountBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => UserAccountRouteRoute,
} as any)
const UserAccountAccountRoute = UserAccountAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => UserAccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$user': typeof UserDashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/callback': typeof authCallbackRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/about': typeof marketingAboutRoute
  '/features': typeof marketingFeaturesRoute
  '/': typeof marketingIndexRoute
  '/$user/account': typeof UserAccountAccountRoute
  '/$user/billing': typeof UserAccountBillingRoute
  '/$user/connections': typeof UserAccountConnectionsRoute
  '/$user/notifications': typeof UserAccountNotificationsRoute
  '/$user/profile': typeof UserAccountProfileRoute
  '/$user/settings': typeof UserAccountSettingsRoute
  '/$user/coach': typeof UserChatCoachRoute
  '/$user/activities': typeof UserDashboardActivitiesRoute
  '/$user/plan': typeof UserDashboardPlanRoute
  '/$user/today': typeof UserDashboardTodayRoute
}
export interface FileRoutesByTo {
  '/$user': typeof UserDashboardRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/callback': typeof authCallbackRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/about': typeof marketingAboutRoute
  '/features': typeof marketingFeaturesRoute
  '/': typeof marketingIndexRoute
  '/$user/account': typeof UserAccountAccountRoute
  '/$user/billing': typeof UserAccountBillingRoute
  '/$user/connections': typeof UserAccountConnectionsRoute
  '/$user/notifications': typeof UserAccountNotificationsRoute
  '/$user/profile': typeof UserAccountProfileRoute
  '/$user/settings': typeof UserAccountSettingsRoute
  '/$user/coach': typeof UserChatCoachRoute
  '/$user/activities': typeof UserDashboardActivitiesRoute
  '/$user/plan': typeof UserDashboardPlanRoute
  '/$user/today': typeof UserDashboardTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$user': typeof UserRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/$user/_account': typeof UserAccountRouteRouteWithChildren
  '/$user/_chat': typeof UserChatRouteRouteWithChildren
  '/$user/_dashboard': typeof UserDashboardRouteRouteWithChildren
  '/(auth)/callback': typeof authCallbackRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(marketing)/about': typeof marketingAboutRoute
  '/(marketing)/features': typeof marketingFeaturesRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/$user/_account/account': typeof UserAccountAccountRoute
  '/$user/_account/billing': typeof UserAccountBillingRoute
  '/$user/_account/connections': typeof UserAccountConnectionsRoute
  '/$user/_account/notifications': typeof UserAccountNotificationsRoute
  '/$user/_account/profile': typeof UserAccountProfileRoute
  '/$user/_account/settings': typeof UserAccountSettingsRoute
  '/$user/_chat/coach': typeof UserChatCoachRoute
  '/$user/_dashboard/activities': typeof UserDashboardActivitiesRoute
  '/$user/_dashboard/plan': typeof UserDashboardPlanRoute
  '/$user/_dashboard/today': typeof UserDashboardTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$user'
    | '/onboarding'
    | '/callback'
    | '/login'
    | '/signup'
    | '/about'
    | '/features'
    | '/'
    | '/$user/account'
    | '/$user/billing'
    | '/$user/connections'
    | '/$user/notifications'
    | '/$user/profile'
    | '/$user/settings'
    | '/$user/coach'
    | '/$user/activities'
    | '/$user/plan'
    | '/$user/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$user'
    | '/onboarding'
    | '/callback'
    | '/login'
    | '/signup'
    | '/about'
    | '/features'
    | '/'
    | '/$user/account'
    | '/$user/billing'
    | '/$user/connections'
    | '/$user/notifications'
    | '/$user/profile'
    | '/$user/settings'
    | '/$user/coach'
    | '/$user/activities'
    | '/$user/plan'
    | '/$user/today'
  id:
    | '__root__'
    | '/$user'
    | '/(auth)'
    | '/(marketing)'
    | '/onboarding'
    | '/$user/_account'
    | '/$user/_chat'
    | '/$user/_dashboard'
    | '/(auth)/callback'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(marketing)/about'
    | '/(marketing)/features'
    | '/(marketing)/'
    | '/$user/_account/account'
    | '/$user/_account/billing'
    | '/$user/_account/connections'
    | '/$user/_account/notifications'
    | '/$user/_account/profile'
    | '/$user/_account/settings'
    | '/$user/_chat/coach'
    | '/$user/_dashboard/activities'
    | '/$user/_dashboard/plan'
    | '/$user/_dashboard/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserRouteRoute: typeof UserRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user': {
      id: '/$user'
      path: '/$user'
      fullPath: '/$user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/features': {
      id: '/(marketing)/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof marketingFeaturesRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/about': {
      id: '/(marketing)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof marketingAboutRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/callback': {
      id: '/(auth)/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof authCallbackRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/$user/_dashboard': {
      id: '/$user/_dashboard'
      path: ''
      fullPath: '/$user'
      preLoaderRoute: typeof UserDashboardRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/$user/_chat': {
      id: '/$user/_chat'
      path: ''
      fullPath: '/$user'
      preLoaderRoute: typeof UserChatRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/$user/_account': {
      id: '/$user/_account'
      path: ''
      fullPath: '/$user'
      preLoaderRoute: typeof UserAccountRouteRouteImport
      parentRoute: typeof UserRouteRoute
    }
    '/$user/_dashboard/today': {
      id: '/$user/_dashboard/today'
      path: '/today'
      fullPath: '/$user/today'
      preLoaderRoute: typeof UserDashboardTodayRouteImport
      parentRoute: typeof UserDashboardRouteRoute
    }
    '/$user/_dashboard/plan': {
      id: '/$user/_dashboard/plan'
      path: '/plan'
      fullPath: '/$user/plan'
      preLoaderRoute: typeof UserDashboardPlanRouteImport
      parentRoute: typeof UserDashboardRouteRoute
    }
    '/$user/_dashboard/activities': {
      id: '/$user/_dashboard/activities'
      path: '/activities'
      fullPath: '/$user/activities'
      preLoaderRoute: typeof UserDashboardActivitiesRouteImport
      parentRoute: typeof UserDashboardRouteRoute
    }
    '/$user/_chat/coach': {
      id: '/$user/_chat/coach'
      path: '/coach'
      fullPath: '/$user/coach'
      preLoaderRoute: typeof UserChatCoachRouteImport
      parentRoute: typeof UserChatRouteRoute
    }
    '/$user/_account/settings': {
      id: '/$user/_account/settings'
      path: '/settings'
      fullPath: '/$user/settings'
      preLoaderRoute: typeof UserAccountSettingsRouteImport
      parentRoute: typeof UserAccountRouteRoute
    }
    '/$user/_account/profile': {
      id: '/$user/_account/profile'
      path: '/profile'
      fullPath: '/$user/profile'
      preLoaderRoute: typeof UserAccountProfileRouteImport
      parentRoute: typeof UserAccountRouteRoute
    }
    '/$user/_account/notifications': {
      id: '/$user/_account/notifications'
      path: '/notifications'
      fullPath: '/$user/notifications'
      preLoaderRoute: typeof UserAccountNotificationsRouteImport
      parentRoute: typeof UserAccountRouteRoute
    }
    '/$user/_account/connections': {
      id: '/$user/_account/connections'
      path: '/connections'
      fullPath: '/$user/connections'
      preLoaderRoute: typeof UserAccountConnectionsRouteImport
      parentRoute: typeof UserAccountRouteRoute
    }
    '/$user/_account/billing': {
      id: '/$user/_account/billing'
      path: '/billing'
      fullPath: '/$user/billing'
      preLoaderRoute: typeof UserAccountBillingRouteImport
      parentRoute: typeof UserAccountRouteRoute
    }
    '/$user/_account/account': {
      id: '/$user/_account/account'
      path: '/account'
      fullPath: '/$user/account'
      preLoaderRoute: typeof UserAccountAccountRouteImport
      parentRoute: typeof UserAccountRouteRoute
    }
  }
}

interface UserAccountRouteRouteChildren {
  UserAccountAccountRoute: typeof UserAccountAccountRoute
  UserAccountBillingRoute: typeof UserAccountBillingRoute
  UserAccountConnectionsRoute: typeof UserAccountConnectionsRoute
  UserAccountNotificationsRoute: typeof UserAccountNotificationsRoute
  UserAccountProfileRoute: typeof UserAccountProfileRoute
  UserAccountSettingsRoute: typeof UserAccountSettingsRoute
}

const UserAccountRouteRouteChildren: UserAccountRouteRouteChildren = {
  UserAccountAccountRoute: UserAccountAccountRoute,
  UserAccountBillingRoute: UserAccountBillingRoute,
  UserAccountConnectionsRoute: UserAccountConnectionsRoute,
  UserAccountNotificationsRoute: UserAccountNotificationsRoute,
  UserAccountProfileRoute: UserAccountProfileRoute,
  UserAccountSettingsRoute: UserAccountSettingsRoute,
}

const UserAccountRouteRouteWithChildren =
  UserAccountRouteRoute._addFileChildren(UserAccountRouteRouteChildren)

interface UserChatRouteRouteChildren {
  UserChatCoachRoute: typeof UserChatCoachRoute
}

const UserChatRouteRouteChildren: UserChatRouteRouteChildren = {
  UserChatCoachRoute: UserChatCoachRoute,
}

const UserChatRouteRouteWithChildren = UserChatRouteRoute._addFileChildren(
  UserChatRouteRouteChildren,
)

interface UserDashboardRouteRouteChildren {
  UserDashboardActivitiesRoute: typeof UserDashboardActivitiesRoute
  UserDashboardPlanRoute: typeof UserDashboardPlanRoute
  UserDashboardTodayRoute: typeof UserDashboardTodayRoute
}

const UserDashboardRouteRouteChildren: UserDashboardRouteRouteChildren = {
  UserDashboardActivitiesRoute: UserDashboardActivitiesRoute,
  UserDashboardPlanRoute: UserDashboardPlanRoute,
  UserDashboardTodayRoute: UserDashboardTodayRoute,
}

const UserDashboardRouteRouteWithChildren =
  UserDashboardRouteRoute._addFileChildren(UserDashboardRouteRouteChildren)

interface UserRouteRouteChildren {
  UserAccountRouteRoute: typeof UserAccountRouteRouteWithChildren
  UserChatRouteRoute: typeof UserChatRouteRouteWithChildren
  UserDashboardRouteRoute: typeof UserDashboardRouteRouteWithChildren
}

const UserRouteRouteChildren: UserRouteRouteChildren = {
  UserAccountRouteRoute: UserAccountRouteRouteWithChildren,
  UserChatRouteRoute: UserChatRouteRouteWithChildren,
  UserDashboardRouteRoute: UserDashboardRouteRouteWithChildren,
}

const UserRouteRouteWithChildren = UserRouteRoute._addFileChildren(
  UserRouteRouteChildren,
)

interface authRouteRouteChildren {
  authCallbackRoute: typeof authCallbackRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authCallbackRoute: authCallbackRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface marketingRouteRouteChildren {
  marketingAboutRoute: typeof marketingAboutRoute
  marketingFeaturesRoute: typeof marketingFeaturesRoute
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingAboutRoute: marketingAboutRoute,
  marketingFeaturesRoute: marketingFeaturesRoute,
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  UserRouteRoute: UserRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  marketingRouteRoute: marketingRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
