/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-file /home/madvib/dev/bene/.dev.vars` (hash: 2bb7d694af955fc5e00b33a853257d67)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "UserHub";
	}
	interface Env {
		NEXTJS_ENV: string;
		WORKOUT_SESSION: DurableObjectNamespace<import("./src/index").WorkoutSession>;
		AI_SERVICE: Fetcher /* ai-service */;
		EVENT_BUS: Fetcher /* event-bus */;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV">> {}
}
declare module "*.sql" {
	const value: string;
	export default value;
}