export {
  // PlanGoals exports
  createPlanGoals,
  createEventTraining,
  createStrengthBuilding,
  createHabitBuilding,
  hasTargetDate,
  hasTargetWeights,
  hasTargetPace,
  hasTargetDistance,
  hasTargetWorkouts,
  hasTargetStreak,
  isEventTraining,
  isStrengthFocused,
  isConsistencyFocused,
  daysUntilTarget,
  weeksUntilTarget,
  getTargetWeightForExercise,
  getAllTargetExercises,
  withNewTargetDate,
  withUpdatedPrimaryGoal,
  withAdditionalSecondaryGoal,
  withUpdatedTargetPace,
  withUpdatedTargetWeight,
  withAdjustedTargetMetrics,
  getPrimaryGoalDescription,
  getFullDescription,
  getMetricsSummary,
  equals as planGoalsEquals
} from './value-objects/plan-goals/plan-goals.js';

export {
  // WorkoutActivity exports
  createWorkoutActivity,
  createWarmup,
  createCooldown,
  createDistanceRun,
  createIntervalSession,
  createCircuit,
  isWarmup,
  isCooldown,
  isMainActivity,
  isIntervalBased as isIntervalBasedActivity,
  isCircuit as isCircuitActivity,
  requiresEquipment as activityRequiresEquipment,
  hasEquipment as activityHasEquipment,
  getEquipmentList,
  hasStructure as activityHasStructure,
  hasInstructions as activityHasInstructions,
  hasVideo as activityHasVideo,
  hasAlternatives as activityHasAlternatives,
  getEstimatedDuration,
  getEstimatedCalories,
  withDifferentDuration,
  withDifferentDistance,
  withDifferentPace,
  withStructure as workoutActivityWithStructure,
  withAdditionalInstruction,
  withVideo,
  withAlternative,
  withNewOrder,
  adjustForFatigue,
  makeEasier,
  makeHarder,
  getShortDescription as getActivityShortDescription,
  getDetailedDescription as getActivityDetailedDescription,
  getInstructionsList as getActivityInstructionsList
} from './value-objects/workout-activity/workout-activity.js';

export {
  // ProgressionStrategy exports
  createProgressionStrategy,
  createLinearProgression,
  createUndulatingProgression,
  createAdaptiveProgression,
  createConservativeProgression,
  createAggressiveProgression,
  isLinear,
  isUndulating,
  isAdaptive,
  isConservative as isProgressionConservative,
  calculateNextWeekLoad,
  calculateAdaptiveLoad,
  calculateNextWeekWeight,
  calculateNextWeekVolume,
  calculateNextWeekDistance,
  calculateNextWeekPace,
  isDeloadWeek,
  getNextDeloadWeek,
  weeksUntilDeload,
  isTestWeek,
  getNextTestWeek,
  convertToConservative,
  convertToAggressive,
  getDescription as getProgressionDescription
} from './value-objects/progression-strategy/progression-strategy.js';

export {
  // PlanPosition exports
  createPlanPosition,
  createPlanPositionAtStart,
  advanceDay,
  advanceDays,
  advanceWeek,
  advanceWeeks,
  goToNextMonday,
  goToStartOfWeek,
  goToEndOfWeek,
  isBefore,
  isAfter,
  isSamePosition,
  isSameWeek,
  isSameDay,
  isStartOfWeek,
  isEndOfWeek,
  daysUntil,
  weeksUntil,
  isWithinDays,
  isWithinWeeks,
  getDayName,
  isWeekday,
  isWeekend,
  toString as positionToString,
  toShortString as positionToShortString,
  getDisplayInfo,
  equals as positionEquals
} from './value-objects/plan-position/plan-position.js';

export {
  // ActivityStructure exports
  createActivityStructure,
  createEmptyActivityStructure,
  createActivityStructureWithIntervals,
  createActivityStructureWithExercises,
  isIntervalBased as structureIsIntervalBased,
  isExerciseBased,
  isEmpty as structureIsEmpty,
  getTotalDuration as getTotalStructureDuration,
  getTotalSets,
  withAdjustedDuration as structureWithAdjustedDuration,
  withAdjustedIntensity as structureWithAdjustedIntensity,
  withAdditionalRounds,
  withFewerRounds,
  withIncreasedRest as structureWithIncreasedRest,
  getAverageIntensity,
  requiresEquipment as structureRequiresEquipment,
  getDescription as getStructureDescription,
  equals as structureEquals
} from './value-objects/activity-structure/activity-structure.js';

export {
  // TrainingConstraints exports
  createTrainingConstraints,
  createHomeTrainingConstraints,
  createGymTrainingConstraints,
  createInjuryConstraints,
  hasInjuries,
  getReportedInjuries,
  isInjurySeverity,
  canExercise,
  hasEquipment as constraintsHasEquipment,
  canTrainAtTime,
  isAvailableDay,
  getAvailableDaysCount,
  getMaxTrainingHoursPerWeek,
  isLocationAvailable,
  getDaysUntilNextAvailable,
  withAddedEquipment,
  withAddedAvailableDay,
  withAddedInjury,
  withExtendedDuration,
  withNewLocation,
  withoutInjury,
  getWeeklyTrainingAvailability,
  getEquipmentAvailabilityScore,
  getInjuryRiskScore,
  validateAgainstConstraints,
  getConstraintSummary,
  equals as constraintsEquals
} from './value-objects/training-constraints/training-constraints.js';

export {
  // WorkoutGoals exports
  createWorkoutGoals,
  createDistanceWorkout,
  createDurationWorkout,
  createVolumeWorkout,
  hasDistanceGoal,
  hasDurationGoal,
  hasVolumeGoal,
  isCompletionRequired,
  hasMinimumEffort,
  isAutoVerifiable,
  getMinimumEffort,
  getGoalType,
  getDistanceValue,
  getDurationValue,
  getVolumeSets,
  getVolumeReps,
  withDistanceGoal,
  withDurationGoal,
  withVolumeGoal,
  withUpdatedCompletionCriteria,
  withMinimumEffort,
  withAutoVerification,
  getExpectedWorkoutTime,
  getGoalDifficulty,
  isValidForBeginner,
  isValidForAdvanced,
  getGoalDescription,
  getIntensityDescription,
  equals as workoutGoalsEquals
} from './value-objects/workout-goals/workout-goals.js';

export * from './errors/workout-plan-errors.js';
