/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc --env-file /home/madvib/dev/bene/.dev.vars` (hash: 895846bb929da44c1f29259d6fce7b36)
export {};
declare global {
	const NODE_ENV: string;
}
