/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc --env-file /home/madvib/dev/bene/.env.local` (hash: 205ee3f44e8de6c9260e8de100ac0625)
export {};
declare global {
	const VITE_API_BASE_URL: string;
	const CLOUDFLARE_ACCOUNT_ID: string;
	const CLOUDFLARE_USER_AUTH_DATABASE_ID: string;
	const CLOUDFLARE_D1_TOKEN: string;
}
