/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-file /home/madvib/dev/bene/.dev.vars` (hash: a66997692dcd225a4fd233e69524c209)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		NEXTJS_ENV: string;
		USER_HUB: DurableObjectNamespace /* UserHub from user-hub-worker */;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV">> {}
}
