/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc -c /home/madvib/dev/bene/apps/actors/user-hub/wrangler.jsonc -c /home/madvib/dev/bene/apps/actors/workout-session/wrangler.jsonc --env-file /home/madvib/dev/bene/.env.local --env-file .dev.vars` (hash: 9ece1835d5d125571b468f8fb68a37df)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		VITE_API_BASE_URL: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_USER_AUTH_DATABASE_ID: string;
		CLOUDFLARE_D1_TOKEN: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		USER_HUB: DurableObjectNamespace<import("../actors/user-hub/src/index").UserHub>;
		WORKOUT_SESSION: DurableObjectNamespace<import("../actors/workout-session/src/index").WorkoutSession>;
		DB_USER_AUTH: D1Database;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VITE_API_BASE_URL" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_USER_AUTH_DATABASE_ID" | "CLOUDFLARE_D1_TOKEN" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL">> {}
}
