/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc --env-file /home/madvib/dev/bene/.dev.vars` (hash: f63c1ab9b68dbf48c1187678db69337c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		NODE_ENV: string;
		DOMAIN_EVENTS_QUEUE: Queue;
		EMAIL_QUEUE: Queue;
		ANALYTICS_QUEUE: Queue;
		INTEGRATION_SYNC_QUEUE: Queue;
	}
}
interface Env extends Cloudflare.Env {}
