/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-env.d.ts --include-runtime=false -c ./wrangler.jsonc --env-file /home/madvib/dev/bene/.env.local` (hash: 586589618abe168c0c7758a176e66d0b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		VITE_API_BASE_URL: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_USER_AUTH_DATABASE_ID: string;
		CLOUDFLARE_D1_TOKEN: string;
	}
}
interface Env extends Cloudflare.Env {}
