/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false -c ./wrangler.jsonc --env-file /home/madvib/dev/bene/.dev.vars` (hash: 25c8738efde721da91aa6e670a3a01a5)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		NODE_ENV: string;
	}
}
interface Env extends Cloudflare.Env {}
